### ISSUE TITLE
Make import of default styles optional

### ISSUE THREAD

**Issue by hacknug** [zernonia/vue3-notion#12]
**Is your feature request related to a problem? Please describe.**
I'd like a way to opt-in/opt-out of importing the default stylesheet.

**Describe the solution you'd like**
Ideally we would get this from the user module `options` and conditionally push the css import depending on value. Maybe use a boolean to enable/disable default styles and accept a string too to automatically import this for the user (not sure if the string option is really necessary, just a thought).

**Describe alternatives you've considered**
Not sure there is any alternative.

**Additional context**
https://github.com/zernonia/vue3-notion/blob/34026f65fea3611b89fe2f1360c653505ec877a1/nuxt/index.ts#L21

**Comment by zernonia** [comment]
Hi @hacknug . You are right! By default it shouldn't include css. I missed out that part for Nuxt module. 
Yup I will add option to the modules to enable css.
