### ISSUE TITLE
 Failed to load

### ISSUE THREAD

**Issue by DROWNING2003** [zernonia/vue3-notion#22]
![image](https://user-images.githubusercontent.com/67043893/169507105-da01d90d-be2b-43c5-ba73-0cdac270efe1.png)
![image](https://user-images.githubusercontent.com/67043893/169507185-6e6c2635-5e02-40a5-9277-6287e016fc68.png)

**Comment by zernonia** [comment]
@DROWNING2003  Please provide a minimal reproduction for this issue

**Comment by zernonia** [comment]
Close due to no minimal reproduction or pageId provided
