### ISSUE TITLE
Child blocks are not rendering

### ISSUE THREAD

**Issue by barisener** [zernonia/vue3-notion#27]
**Describe the bug**
When i add a content to block in a page with notion api, the library does not render these content. I checked the response and my contents was there as response but i can not see it on page. it is not rendering.

**To Reproduce**
1. Go to notion and create a new page.
2. Add contents manuel and append a new block as child block with notion api to your page.
3. Share it and use the library (vue3-notion) to render your notion page in a vue app

**Expected behavior**
I expect my child blocks render in my page.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 103.0.5060.134

**Comment by zernonia** [comment]
Hi @barisener ! could you please share what block you inserted using Notion API? Best if you could share a pageId
