### ISSUE TITLE
Error on installing the package

### ISSUE THREAD

**Issue by JacomoJ** [zernonia/vue3-notion#29]
I was trying to install `vue3-notion` to the existing vue3 project but the following error message appeared when I was trying to add it using yarn: 
**Describe the bug**
```
yarn add vue3-notion  
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
error An unexpected error occurred: "expected hoisted manifest for \"vue3-notion#vue#@vue/server-renderer#@vue/compiler-ssr\"".
```

**Desktop (please complete the following information):**
- MacOs

I search on web but no solution found, anyone faced this issue as well?

Thank you guys in advance.

**Comment by zernonia** [comment]
Seems like an issue with yarn. perhaps try this solution [here](https://github.com/MaxLeiter/sortablejs-vue3/issues/1)?

**Comment by JacomoJ** [comment]
> Seems like an issue with yarn. perhaps try this solution [here](https://github.com/MaxLeiter/sortablejs-vue3/issues/1)?

Ok thank you!
