### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by brachkow** [zernonia/vue3-notion#30]
**Describe the bug**
While this project is written in TS, it does not automatically provide types so any import results in this error:
```
error TS7016: Could not find a declaration file for module 'vue3-notion'. '/home/runner/work/example/node_modules/vue3-notion/dist/index.umd.js' implicitly has an 'any' type
```

**To Reproduce**
1. Import NotionRenderer to Vue3 SFC 
```
<script lang="ts" setup>
  import { NotionRenderer } from 'vue3-notion';
</script>

<template>
  <NotionRenderer />
</template>
```
2. Run typecheck
3. See error

**Expected behavior**
No type error

**Comment by zernonia** [comment]
Hi @brachkow . NotionRenderer require props, that why Typescript is shouting for type error. Please see [Basic Example](https://github.com/zernonia/vue3-notion#basic-example-for-vue-3).

Do let me know if issue persist ya

**Comment by brachkow** [comment]
It was minimal example, so I striped down props. Actual problem is on import level.

You can see [real world example](https://github.com/tough-dev-school/lms-frontend-v2/pull/192/files#diff-d3314b6298370d8a4d3ee39e5671480b9a576814991185cba6450dfed197b9d9) and [its error message](https://github.com/tough-dev-school/lms-frontend-v2/actions/runs/4099923626/jobs/7070284014#step:7:11) there.

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/33203187/216873452-9672d580-e4a0-45b8-a204-32752e4776de.png">
