### ISSUE TITLE
could not render list(ordered list & numbered list)

### ISSUE THREAD

**Issue by alanchenchen** [zernonia/vue3-notion#46]
**Describe the bug**
could not render numbered list or ordered list

**To Reproduce**
1. Go to [https://www.f1hire.com/blog/9557d426-6e50-42e7-bbc9-1fbaff37cb3a](https://www.f1hire.com/blog/9557d426-6e50-42e7-bbc9-1fbaff37cb3a)
2. See error
```js
index-DUgme8w3.js:1 TypeError: Cannot read properties of undefined (reading 'content')
    at code-41222ca7-Dn1vmtUA.js:1:468
    at Array.forEach (<anonymous>)
    at wn (code-41222ca7-Dn1vmtUA.js:1:436)
    at kn (code-41222ca7-Dn1vmtUA.js:1:644)
    at code-41222ca7-Dn1vmtUA.js:243:46214
    at hd.fn (index-DUgme8w3.js:1:12660)
    at hd.run (index-DUgme8w3.js:1:5210)
    at get value (index-DUgme8w3.js:1:12882)
    at Ct (index-DUgme8w3.js:1:13755)
    at Proxy.<anonymous> (code-41222ca7-Dn1vmtUA.js:243:46677)
```
3. Only list disappeared

**Screenshots**
notion original page:
https://wholeren.notion.site/Intern-series-How-to-Activate-Your-CPT-and-What-To-Keep-In-Mind-9557d4266e5042e7bbc91fbaff37cb3a

**Desktop (please complete the following information):**
 - OS:  MacOS
 - Browser: chrome
 - Version: 128.0.6613.114

**Additional context**

**Comment by zernonia** [comment]
Fixed https://github.com/zernonia/vue3-notion/commit/43eb4a577d3e70351d4c067820930c0ff6bdeead

https://vue3-notion-preview.vercel.app/9557d4266e5042e7bbc91fbaff37cb3a
